jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Remove any cached Python files (.pyc, __pycache__)
      - name: Clean Python cache
        run: |
          find . -name "*.pyc" -exec rm -f {} \;
          find . -name "__pycache__" -exec rm -rf {} \;

      # Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Or whatever version you're using

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Or use unittest if needed
